### PR TITLE
Fix #1584: throw exception when attempting to access the System after finalizeFromProperties

### LINKED ISSUE #1584: Cryptic exception message if finalizeFromProperties() called after initSystem()
To reproduce:
```cpp
#include <OpenSim/OpenSim.h>
using namespace SimTK;
using namespace OpenSim;

int main() {
    try {
        auto model = Model("gait10dof18musc.osim");
        auto state = model.initSystem();
        //model.finalizeFromProperties(); //frog
        RungeKuttaMersonIntegrator integrator(model.getSystem());
        Manager manager(model, integrator);
        state.setTime(0.);
        manager.integrate(state, 1.);
    } catch (const std::exception& ex) {
        std::cout << ex.what() << std::endl;
        return 1;
    }
    return 0;
}
```
When :frog: is uncommented, the following exception message is reported:
<pre>
SimTK Exception thrown at Integrator.cpp:431:
  Integrator initialization failed apparently because:
Component::isCacheVariableValid: ERR- name not found.
 for component 'geometrypath_' of type GeometryPath
</pre>
Although this example may seem contrived, it was discovered in a "real world" situation in testWrapping.cpp (`simulateModelWithMusclesNoViz()`), where `Model::printBasicInfo()` was being called after `Model::initSystem()` (and `printBasicInfo()` must now be preceded by `finalizeFromProperties()` due to #1582).

There are at least two possible resolutions:
1. Make `Model::finalizeFromProperties()` "harmless" if the model hasn't changed. In the example above, `initSystem()` had just been called, so it doesn't seem like `finalizeFromProperties()` should do much of anything. If that's not possible, then…
2. Catch the exception from Integrator and provide a more user-friendly message that indicates what went wrong and how the problem might be fixed.

### PR DESCRIPTION
**Pull request by aseth1**
Fixes issue #1584 

In #1584 the `Model` was treating the `System` as valid after `finalizeFromProperties()` was called leading to a cryptic message downstream and failure when attempting to access the cache of an invalid state.

### Brief summary of changes
Key change was to reset the `Component`'s reference to the system in `finalizeFromProperties()` which was already calling its own `reset()`

### Testing I've completed
Originally used code snippet from #1584 to reproduce the failure and corresponding message. 
Then generalized into its own test `testModelInterface` was added to verify the correct behavior when the system or derivatives are accessed on a `Model` but no longer has a `System`.

### Looking for feedback on...
- is the test case adequate

### CHANGELOG.md (choose one)
- no need to update because this is a bug fix with no interface changes

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

File: OpenSim/Common/Component.h [hunk 1]
```diff
@@ -414,13 +414,17 @@ OpenSim_DECLARE_ABSTRACT_OBJECT(Component, Object);
...
+        prior to invoking the virtual extendFinalizeFromProperties() on itself.
+        Note, finalizeFromProperties() disassociates the Component from the
+        System it was added to (result of addToSystem()), which results from
+        calling  Model::initSystem(), for example.*/
     void finalizeFromProperties();
 
-    /** Connect this Component to its aggregate component, which is the root
-        of a tree of components.*/
+    /** Satisfy the Component's connections specified by its Sockets and Inputs.
+        Locate Component and their Outputs to satisfy the connections in an
```
Comment (tkuchida) [inline OpenSim/Common/Component.h]: Component -> Components

File: OpenSim/Common/Component.h [hunk 2]
```diff
@@ -414,13 +414,17 @@ OpenSim_DECLARE_ABSTRACT_OBJECT(Component, Object);
...
+        aggregate Component, which is the root of a tree of Components, which
```
Comment (tkuchida) [inline OpenSim/Common/Component.h]: I think the second ", which…" does more harm than good.

File: OpenSim/Common/Component.h [hunk 3]
```diff
@@ -712,6 +716,7 @@ OpenSim_DECLARE_ABSTRACT_OBJECT(Component, Object);
     */
     template <class C = Component>
     C& updComponent(const std::string& name) {
+        clearObjectIsUpToDateWithProperties();
```
Comment (tkuchida) [inline OpenSim/Common/Component.h]: Does this mean that the simple act of fetching a writable reference to a Component invalidates its up-to-dateness? Maybe that's okay—though users will need to be very careful to use `getComponent()` rather than `updComponent()`: there will be situations where both will work but `updComponent()` will take longer.

Comment (aseth1) [inline OpenSim/Common/Component.h]: Yes, the `upd` methods should be reserved for Component (and Model) editing and not for simulation time querying. I think this makes `updComponent` (and I also made `udComponentList` comply) consistent to write access of `Set`s that are properties. For example, if you access bodies, forces, constraint via their Sets (e.g, `Model::updBodySet()`) these have the same effect of *dirtying* the up-to-date flag.

Comment (tkuchida) [inline OpenSim/Common/Component.h]: > if you access bodies, forces, constraint via their Sets (e.g, `Model::updBodySet()`) these have the same effect of *dirtying* the up-to-date flag.

Ah, ok. I didn't know that.


A separate potential issue:
IIRC `get...()` and `upd...()` can both work in scripting. Is it then possible for an assumption about the up-to-date flag to be incorrect in scripting?

Comment (aseth1) [inline OpenSim/Common/Component.h]: Yes, absolutely- that is a big hole (issue) right now.

**Comment by aseth1** [comment]
> CI failures are due to timeouts only ⌛️

The debug failures were legit. Subsystem handles were having their implementations deleted by the System. The solution was to reset the unique_ptrs to the subsystem handles first (as @chrisdembia did in #585 when the System is recreated) before the System reset.

**Comment by tkuchida** [comment]
> The debug failures were legit.

Crud; I must have just looked at [this one](https://travis-ci.org/opensim-org/opensim-core/jobs/222970381). The dangers of :scream: :speech_balloon: :wolf:

File: OpenSim/Common/Component.h (hunk 3 above)
Comment (tkuchida) [inline OpenSim/Common/Component.h]: Opened #1666 to track.

File: OpenSim/Common/Component.h [hunk 4]
```diff
@@ -704,14 +709,20 @@ OpenSim_DECLARE_ABSTRACT_OBJECT(Component, Object);
         return getComponent<Component>(pathname);
     }
 
-    /** Get a writable reference to a subcomponent.
+    /** Get a writable reference to a subcomponent. Use this method
+    * to edit the properties and connections of the subcomponent.
+    * Note: the method will mark this Component as not up-to-date with
```
Comment (tkuchida) [inline OpenSim/Common/Component.h]: "not up-to-date" -> "out-of-date"?

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+
+using namespace OpenSim;
+using namespace std;
+
+
+int main() {
+    LoadOpenSimLibrary("osimActuators");
+
+    try {
+        // the specific model used here is not important
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: ...but it must contain at least 1 muscle and at least 2 bodies

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+        Model model("arm26.osim");
+        model.finalizeFromProperties();
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Following what you've done below, perhaps precede L39 with
``` cpp
ASSERT(!model.isObjectUpToDateWithProperties());
```

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+
+        // model should be up-to-date with its properties
+        ASSERT(model.isObjectUpToDateWithProperties());
+
+        // make an edit to a Component contained in the model's Set
+        model.updMuscles()[0].upd_min_control() = 0.02;
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: According to the conversation above, it sounds like
``` cpp
model.updMuscles();
```
should be sufficient here to dirty the up-to-date flag, and would be a stricter test.

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 8]
```diff
@@ -0,0 +1,133 @@
...
+        ASSERT(!model.isObjectUpToDateWithProperties());
+
+        model.finalizeFromProperties();
+        ASSERT(model.isObjectUpToDateWithProperties());
+
+        // make an edit to a Component contained in another Set
+        model.updBodySet()[1].upd_mass() = 0.05;
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Again, just `model.updBodySet();`?

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 9]
```diff
@@ -0,0 +1,133 @@
...
+        ASSERT(!model.isObjectUpToDateWithProperties());
+
+        model.finalizeFromProperties();
+        ASSERT(model.isObjectUpToDateWithProperties());
+
+        // make an edit through model's ComponentList access
+        for (auto& body : model.updComponentList<Body>()) {
+            body.upd_mass_center() = SimTK::Vec3(0);
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Perhaps just `break;` at L61 would be sufficient?

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 10]
```diff
@@ -0,0 +1,133 @@
...
+        }
+        ASSERT(!model.isObjectUpToDateWithProperties());
+
+        SimTK::State dummy_state;
+
+        ASSERT_THROW(ComponentHasNoSystem, model.getSystem());
+        ASSERT_THROW(ComponentHasNoSystem, model.realizeDynamics(dummy_state));
+        ASSERT_THROW(ComponentHasNoSystem, 
+                     model.computeStateVariableDerivatives(dummy_state));
+        // should be able to create a Manager either
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: should -> should not

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 11]
```diff
@@ -0,0 +1,133 @@
...
+        // verify that finalizeFromProperties() wipes out the underlying System
+        ASSERT_THROW(ComponentHasNoSystem, model.getSystem());
+
+        // should not be able to "trick" the manager into integrating a model
+        // given a stale but compatible state
+        ASSERT_THROW(ComponentHasNoSystem, manager.integrate(state, 1.));
+
+        state = model.initSystem();
+        //re-establish all the connections in the model
+        model.finalizeConnections(model);
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Why is `model.finalizeConnections(model);` required here? Won't `model.initSystem();` on L89 already have "re-establish[ed] all the connections in the model"?

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 12]
```diff
@@ -0,0 +1,133 @@
...
+
+        // verify that finalizeConnections() does not wipe out the underlying 
+        // System iff there are no changes to the dependencies
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: This logic seems to be the opposite of the logic used to dirty the up-to-date flag. Whereas just the act of touching a writable reference dirties the flag, the logic here appears to be that you can touch the connections without invalidating the downstream product (System). Seems inconsistent when wearing :tophat: (user's hat). Totally fine to address some other time (e.g., see #1668).

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 5 above)
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: …and one of the bodies must be named "r_humerus" (see L98). I would delete this comment.

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 13]
```diff
@@ -0,0 +1,133 @@
...
+        state = model.initSystem();
+
+        // now update the elbow and connect to the new frame
+        Joint& elbow = model.updComponent<Joint>("r_elbow");
+        elbow.connectSocket_parent_frame(*elbowInHumerus);
+
+        // satisfy the new connections in the model
+        model.finalizeConnections(model);
+
+        // now changing the connections should invalidate the System
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: changing -> finalizing. The connections _weren't_ changed the first time, which is precisely why the System remained intact.

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 11 above)
Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: It is not required in the same way calling `finalizeFromProperties()` after `initSystem` is not required. I will update the comment.

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 12 above)
Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: No connection was touched. If a Component is updated in anyway (to change its connection) then the System should be invalidated (that is tested below).

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 7 above)
Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: You are right that updating the model's Set will dirty the flag, but I thought the case of editing a property was more typical.

Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: > I thought the case of editing a property was more typical.

I don't disagree, but if we want to ensure that the flag is dirtied just by calling `model.updMuscles();` (which may not be true in the future if the design ever changes), then I think it's safer to use the stricter test.

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 9 above)
Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: done

**Comment by aseth1** [comment]
@tkuchida let me know if the recent changes addressed your comments.

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 6 above)
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: This comment was neither addressed nor replied to. Is there another test somewhere else that confirms `!model.isObjectUpToDateWithProperties()` immediately after loading a Model, or was the suggestion ignored because it was deemed unnecessary to perform this check?

**Comment by tkuchida** [comment]
> @tkuchida let me know if the recent changes addressed your comments.

One comment was ignored. There are a few possible explanations for this but I don't have enough information to know which is the case.

File: OpenSim/Simulation/Test/testModelInterface.cpp (hunk 6 above)
Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: A newly loaded model is likely to be up-to-date with its properties (and is in this case) if there haven't been any edits.  The job of `finalizeFromProperties` is to initialize internal data structures from properties, and it is necessary to call it after loading.

Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: I must not be explaining my thinking clearly. The `finalizeFromProperties()` method must be called on L39 (after loading the model) because some condition that is required by the API is not met. Is it worthwhile to add an `ASSERT` before L39 to check that the condition is not met and another `ASSERT` _after_ L39 to check that the condition is met after calling `finalizeFromProperties()`? It seems like this test case is intended to check such conditions. Is there another test case elsewhere that is already testing the pre- and post-conditions of `finalizeFromProperties()`?

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 14]
```diff
@@ -0,0 +1,133 @@
...
+
+int main() {
+    LoadOpenSimLibrary("osimActuators");
+
+    try {
+        // the specific model used here is not important
+        Model model("arm26.osim");
+        model.finalizeFromProperties();
+
+        // model should be up-to-date with its properties
```
Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Could explain why. I interpreted this comment to mean that the model should _now_ be up-to-date with its properties—as in, now that `finalizeFromProperties()` has been called. Seems like a reasonable assumption, given the name of the method.

Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: That is right. After `finalizeFromProperties()` the model must be up-to-date with its properties and have all its internals be consistent with its properties. Would you like me to update the comment?

Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: :confused: You replied to my comment on L39 with an apparently contradictory statement. It's probably easiest to sort this out verbally :cow::speech_balloon:

Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: I don't see the contradiction. We cannot assume that the model is *out-of-date* with properties before we call `finalizeFromProperties()` but they must be *up-to-date* after and that is being tested.

Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: What is the pre-condition for `finalizeFromProperties()`? My suggestion is to test the pre-condition for `finalizeFromProperties()` before it's called on L39. This suggestion is to maintain consistency with several of the other tests in this file, which are of the form
- `ASSERT` to test pre-condition for :turtle:
- call :turtle:
- `ASSERT` to test post-condition for :turtle:

Comment (tkuchida) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Taking a step back: I think you and Chris are the only people who understand how the Component API has been designed. I see this test case as an opportunity to communicate the design to future developers—but the same can be accomplished by addressing #890 so I think this PR is :white_check_mark:.

Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: OK, I can add that the ComponentList access (as in counting sub components) must throw prior to calling `finalizeFroProperties()`

File: OpenSim/Simulation/Test/testModelInterface.cpp [hunk 15]
```diff
@@ -0,0 +1,150 @@
...
+
+        model.addComponent(elbowInHumerus);
+
+        // establish the new offset frame as part of the model but not
+        // used by any joints, constraints or forces
+        state = model.initSystem();
+
+        // update the elbow Joint and connect its socket to the new frame
+        Joint& elbow = model.updComponent<Joint>("r_elbow");
+        elbow.connectSocket_parent_frame(*elbowInHumerus);
```
Comment (chrisdembia) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: Consider documenting that this call requires recreating the system. Places where this could be added:

- https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/ComponentSocket.h#L912 and similar functions in other macros.
- https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/ComponentSocket.h#L142 and similar `connect()` functions in derived classes.

Would be good to add a similar check for `connectInput_()`; at the very least, we should add a TODO for that.

Comment (aseth1) [inline OpenSim/Simulation/Test/testModelInterface.cpp]: ATM neither `connectSocket_` nor `connectInput_` themselves invalidated the System. It is the fact that both required a writable `Component` reference and `updComponent`, `updComponentList` or any `upd` of Sets that are properties causes the `Component` to be *out-of-date*.

**Comment by chrisdembia** [comment]
Thanks for editing that comment; feel free to merge.

**Comment by aseth1** [comment]
Thank-you @chrisdembia and @tkuchida . I created a feature request issue to track our discussions about using a call-back on `Object` upon property editing to *dirty* the owning `Model`.
