### PR TITLE
Fix Component counts in Model::print{Basic|Detailed}Info()

### LINKED ISSUE #1551: Model::printBasicInfo() and printDetailedInfo() do not account for components added via addComponent()
The model has some utility functions for printing information about the model, such as the number of joints. However, if a joint was added to the model via `Component::addComponent()`, then it is not accounted for in the output of `printBasicInfo()`, etc.

### PR DESCRIPTION
**Pull request by tkuchida**
Fixes #1551.

Sample output from `Model::printBasicInfo()`
<pre>
               MODEL: gait10dof18musc.osim
         coordinates: 10
              forces: 18
           actuators: 18
             muscles: 18
            analyses: 0
              probes: 0
              bodies: 12
              joints: 12
         constraints: 0
             markers: 0
         controllers: 0
  contact geometries: 0
misc modelcomponents: 0
</pre>

Sample output from `Model::printDetailedInfo()`
<pre>
MODEL: gait10dof18musc.osim

numStates = 56
numCoordinates = 10
numSpeeds = 10
numActuators = 18
numBodies = 12
numConstraints = 0
numProbes = 0

ANALYSES (total: 0)

BODIES (total: 12)
body[0] = pelvis. mass: 11.777
              moments of inertia:  ~[0.1028,0.0871,0.0579]
              products of inertia: ~[0,0,0]
body[1] = femur_r. mass: 9.3014
              moments of inertia:  ~[0.1339,0.0351,0.1412]
              products of inertia: ~[0,0,0]
body[2] = tibia_r. mass: 3.7075
              moments of inertia:  ~[0.0504,0.0051,0.0511]
              products of inertia: ~[0,0,0]
body[3] = talus_r. mass: 0.1
              moments of inertia:  ~[0.001,0.001,0.001]
              products of inertia: ~[0,0,0]
body[4] = calcn_r. mass: 1.25
              moments of inertia:  ~[0.0014,0.0039,0.0041]
              products of inertia: ~[0,0,0]
body[5] = toes_r. mass: 0.2166
              moments of inertia:  ~[0.0001,0.0002,0.0001]
              products of inertia: ~[0,0,0]
body[6] = femur_l. mass: 9.3014
              moments of inertia:  ~[0.1339,0.0351,0.1412]
              products of inertia: ~[0,0,0]
body[7] = tibia_l. mass: 3.7075
              moments of inertia:  ~[0.0504,0.0051,0.0511]
              products of inertia: ~[0,0,0]
body[8] = talus_l. mass: 0.1
              moments of inertia:  ~[0.001,0.001,0.001]
              products of inertia: ~[0,0,0]
body[9] = calcn_l. mass: 1.25
              moments of inertia:  ~[0.0014,0.0039,0.0041]
              products of inertia: ~[0,0,0]
body[10] = toes_l. mass: 0.2166
              moments of inertia:  ~[0.0001,0.0002,0.0001]
              products of inertia: ~[0,0,0]
body[11] = torso. mass: 34.2366
              moments of inertia:  ~[1.4745,0.7555,1.4314]
              products of inertia: ~[0,0,0]

JOINTS (total: 12)
joint[0] = ground_pelvis. parent: ground, child: pelvis
joint[1] = hip_r. parent: pelvis_offset, child: femur_r
joint[2] = knee_r. parent: femur_r, child: tibia_r
joint[3] = ankle_r. parent: tibia_r_offset, child: talus_r
joint[4] = subtalar_r. parent: talus_r_offset, child: calcn_r
joint[5] = mtp_r. parent: calcn_r_offset, child: toes_r
joint[6] = hip_l. parent: pelvis_offset, child: femur_l
joint[7] = knee_l. parent: femur_l, child: tibia_l
joint[8] = ankle_l. parent: tibia_l_offset, child: talus_l
joint[9] = subtalar_l. parent: talus_l_offset, child: calcn_l
joint[10] = mtp_l. parent: calcn_l_offset, child: toes_l
joint[11] = back. parent: pelvis_offset, child: torso

ACTUATORS (total: 18)
actuator[0] = hamstrings_r
actuator[1] = bifemsh_r
actuator[2] = glut_max_r
actuator[3] = iliopsoas_r
actuator[4] = rect_fem_r
actuator[5] = vasti_r
actuator[6] = gastroc_r
actuator[7] = soleus_r
actuator[8] = tib_ant_r
actuator[9] = hamstrings_l
actuator[10] = bifemsh_l
actuator[11] = glut_max_l
actuator[12] = iliopsoas_l
actuator[13] = rect_fem_l
actuator[14] = vasti_l
actuator[15] = gastroc_l
actuator[16] = soleus_l
actuator[17] = tib_ant_l

STATES (total: 56)
y[0] = ground_pelvis/pelvis_tilt/value
y[1] = ground_pelvis/pelvis_tilt/speed
y[2] = ground_pelvis/pelvis_tx/value
y[3] = ground_pelvis/pelvis_tx/speed
y[4] = ground_pelvis/pelvis_ty/value
y[5] = ground_pelvis/pelvis_ty/speed
y[6] = hip_r/hip_flexion_r/value
y[7] = hip_r/hip_flexion_r/speed
y[8] = knee_r/knee_angle_r/value
y[9] = knee_r/knee_angle_r/speed
y[10] = ankle_r/ankle_angle_r/value
y[11] = ankle_r/ankle_angle_r/speed
y[12] = hip_l/hip_flexion_l/value
y[13] = hip_l/hip_flexion_l/speed
y[14] = knee_l/knee_angle_l/value
y[15] = knee_l/knee_angle_l/speed
y[16] = ankle_l/ankle_angle_l/value
y[17] = ankle_l/ankle_angle_l/speed
y[18] = back/lumbar_extension/value
y[19] = back/lumbar_extension/speed
y[20] = hamstrings_r/activation
y[21] = hamstrings_r/fiber_length
y[22] = bifemsh_r/activation
y[23] = bifemsh_r/fiber_length
y[24] = glut_max_r/activation
y[25] = glut_max_r/fiber_length
y[26] = iliopsoas_r/activation
y[27] = iliopsoas_r/fiber_length
y[28] = rect_fem_r/activation
y[29] = rect_fem_r/fiber_length
y[30] = vasti_r/activation
y[31] = vasti_r/fiber_length
y[32] = gastroc_r/activation
y[33] = gastroc_r/fiber_length
y[34] = soleus_r/activation
y[35] = soleus_r/fiber_length
y[36] = tib_ant_r/activation
y[37] = tib_ant_r/fiber_length
y[38] = hamstrings_l/activation
y[39] = hamstrings_l/fiber_length
y[40] = bifemsh_l/activation
y[41] = bifemsh_l/fiber_length
y[42] = glut_max_l/activation
y[43] = glut_max_l/fiber_length
y[44] = iliopsoas_l/activation
y[45] = iliopsoas_l/fiber_length
y[46] = rect_fem_l/activation
y[47] = rect_fem_l/fiber_length
y[48] = vasti_l/activation
y[49] = vasti_l/fiber_length
y[50] = gastroc_l/activation
y[51] = gastroc_l/fiber_length
y[52] = soleus_l/activation
y[53] = soleus_l/fiber_length
y[54] = tib_ant_l/activation
y[55] = tib_ant_l/fiber_length
</pre>

### CODE REVIEW

File: OpenSim/Simulation/Model/Model.h [hunk 1]
```diff
@@ -925,17 +925,17 @@ OpenSim_DECLARE_CONCRETE_OBJECT(Model, ModelComponent);
     /**
      * Print some basic information about the model.
      *
-     * @param aOStream Output stream.
+     * @param aOStream Output stream (e.g., std::cout).
```
Comment (chrisdembia) [inline OpenSim/Simulation/Model/Model.h]: +1.

I also wish the stream had a default argument, so that these functions could be used in MATLAB/python. But that is unrelated to this PR; no need to do anything.

Comment (tkuchida) [inline OpenSim/Simulation/Model/Model.h]: Thanks for reviewing. Good point about the wrapping; I don't mind adding default `std::cout` arguments.

**Comment by chrisdembia** [comment]
Awesome. I still accept.
