### PR TITLE
DelimFileAdapter: exception for empty files.

### LINKED ISSUE #1702: Reading an empty file with CSVFileAdapter causes segfault
Trying to read an empty file (one that exists but is empty) with `CSVFileAdapter` causes a segfault. I have not tested other file adapters.

The following should reproduce the bug:

```
$ touch myfile.csv
$ python
>>> import opensim
>>> opensim.CSVFileAdapter().read('myfile.csv') # <--- segfault
```

Discovered by @nickbianco.

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes #1702 

### Brief summary of changes

This PR adds an exception for when any file read by a `DelimFileAdapter` is empty.

### Testing I've completed

Added a test in `testSTOFileAdapter` to catch an exception when trying to read an empty file. Since the `DelimFileAdapter` is the base for STO, CSV, etc., I don't think it is necessary to separately test CSV files, etc.

### CHANGELOG.md (choose one)

- no need to update because...we haven't released the adapters yet

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

File: OpenSim/Common/DelimFileAdapter.h [hunk 1]
```diff
@@ -360,6 +364,8 @@ DelimFileAdapter<T>::extendRead(const std::string& fileName) const {
     // Read the line containing column labels and fill up the column labels
     // container.
     auto column_labels = nextLine();
+    OPENSIM_THROW_IF(column_labels.size() == 0, Exception,
+                     "No column labels detectedin file '" + fileName + "'.");
```
Comment (tkuchida) [inline OpenSim/Common/DelimFileAdapter.h]: `detectedin` -> `detected in`

Comment (chrisdembia) [inline OpenSim/Common/DelimFileAdapter.h]: Oops; coding while 😪

Comment (tkuchida) [inline OpenSim/Common/DelimFileAdapter.h]: :sheep: :one: :sheep: :two: :sheep: :three: :zzz:

**Comment by chrisdembia** [comment]
Thank you!
