### PR TITLE
Prevent repeated throws from subcomponents when invalid Muscle properties are set

### LINKED ISSUE #2106: Exception thrown when optimal fiber length is zero (in GUI)
When you (accidently) set optimal fiber length to zero in the GUI you get an (expected) exception. 

However, when you try to correct the error, you can't. Exceptions keep getting thrown and you can't change to a non-zero value

screen shot 2018-02-26 at 12 13 05 pm

### PR DESCRIPTION
**Pull request by tkuchida**
Fixes #2106. Redo of PR #2161 using different design.

### Brief summary of changes
Affects `Thelen2003Muscle` and `Millard2012EquilibriumMuscle`, each of which has two subcomponents: `MuscleFixedWidthPennationModel` and `MuscleFirstOrderActivationDynamicModel`.
- Muscles propagate their properties down to their subcomponents and call `finalizeFromProperties()` on each subcomponent; if an exception is thrown, the Muscle restores the subcomponent's properties to their previous (though now out-of-sync) values and re-throws the exception. Underlying issue noted in #2162 for post-4.0.
- Replaced property checks in subcomponents with `OPENSIM_THROW_IF_FRMOBJ` macro that throws only `InvalidPropertyValue` so that the Muscles can catch this exception (rather than potentially catching and misinterpreting a SimTK exception caught with `SimTK::Exception::Base`). Updated corresponding tests.
- Added informative messages when throwing `InvalidPropertyValue` exception.
- Fixed inconsistency in Millard2012EquilibriumMuscle property checking.

### Testing I've completed
Added tests to testMuscles. All tests pass locally.

### CHANGELOG.md (choose one)

- no need to update because... fixes MCI-related bug.
- updated...

The Doxygen for this PR can be viewed at http://myosin.sourceforge.net/?C=N;O=D; click the folder whose name is this PR's number.

### CODE REVIEW

**Comment by tkuchida** [comment]
Tests pass on Travis; the :x: is the familiar error on osx (`/usr/bin/python: No module named nose`) :nose:

File: OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp [hunk 1]
```diff
@@ -147,34 +147,44 @@ void Millard2012EquilibriumMuscle::extendFinalizeFromProperties()
...
         updMemberSubcomponent<MuscleFixedWidthPennationModel>(penMdlIdx);
+    MuscleFixedWidthPennationModel* penMdlCopy = penMdl.clone();
     penMdl.set_optimal_fiber_length(getOptimalFiberLength());
     penMdl.set_pennation_angle_at_optimal(getPennationAngleAtOptimalFiberLength());
     penMdl.set_maximum_pennation_angle(get_maximum_pennation_angle());
+    try {
+        penMdl.finalizeFromProperties();
+    } catch (const InvalidPropertyValue& ex) {
+        penMdl = *penMdlCopy;
+        throw(ex);
```
[the remark this answers is not in the document]
Comment (tkuchida) [reply OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: Ah ok, good point. I'll just `throw;` :baseball:

File: OpenSim/Actuators/MuscleFirstOrderActivationDynamicModel.cpp [hunk 2]
```diff
@@ -97,15 +97,17 @@ void MuscleFirstOrderActivationDynamicModel::extendFinalizeFromProperties()
...
-        "MuscleFirstOrderActivationDynamicModel::extendFinalizeFromProperties",
-        "%s: Deactivation time constant must be greater than zero",
-        getName().c_str());
-    SimTK_VALUECHECK_ALWAYS(0.0, get_minimum_activation(),
-        1.0-SimTK::SignificantReal, "minimum_activation",
-        errorLocation.c_str());
+    OPENSIM_THROW_IF_FRMOBJ(
+        get_activation_time_constant() < SimTK::SignificantReal,
+        InvalidPropertyValue,
+        getProperty_activation_time_constant().getName());
```
[the remark this answers is not in the document]
Comment (tkuchida) [reply OpenSim/Actuators/MuscleFirstOrderActivationDynamicModel.cpp]: Fixed here and elsewhere.

File: OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp [hunk 3]
```diff
@@ -147,34 +151,44 @@ void Millard2012EquilibriumMuscle::extendFinalizeFromProperties()
...
-    // maximum_pennation_angle are checked by
-    // MuscleFixedWidthPennationModel::extendFinalizeFromProperties().
+    // Propagate properties down to pennation model subcomponent. If any of the
+    // new property values are invalid, restore the subcomponent's current
+    // property values (to avoid throwing again when the subcomponent's
+    // extendFinalizeFromProperties() method is called directly) and then
+    // re-throw the exception thrown by the subcomponent.
     auto& penMdl =
         updMemberSubcomponent<MuscleFixedWidthPennationModel>(penMdlIdx);
+    MuscleFixedWidthPennationModel* penMdlCopy = penMdl.clone();
```
Comment (chrisdembia) [inline OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: This memory is leaked (ditto for `actMdlCopy`). Consider:

```cpp
std::unique_ptr<MuscleFixedWidthPennationModel> penMdlCopy(penMdl.clone());
```

(no need to change the copy assignment below; it will work as-is).

An alternative is to use the copy constructor:

```cpp
MuscleFixedWidthPennationModel penMdlCopy(penMdl);
```

Side note: The pattern of cloning and restoring is fine here because the specific subcomponent doesn't have sockets or add anything to the system; I'm not sure this pattern would work for a subcomponent with state variables.

File: OpenSim/Actuators/Thelen2003Muscle.cpp [hunk 4]
```diff
@@ -102,24 +102,46 @@ void Thelen2003Muscle::extendFinalizeFromProperties()
...
+    } catch (const InvalidPropertyValue&) {
+        pennMdl = *pennMdlCopy;
+        throw;
+    }
 
+    // Propagate properties down to activation dynamics model subcomponent.
+    // Handle invalid properties as above for pennation model.
     auto& actMdl =
         updMemberSubcomponent<MuscleFirstOrderActivationDynamicModel>(actMdlIdx);
+    MuscleFirstOrderActivationDynamicModel* actMdlCopy = actMdl.clone();
```
Comment (chrisdembia) [inline OpenSim/Actuators/Thelen2003Muscle.cpp]: See comment above about the memory leak.

File: OpenSim/Simulation/Wrap/WrapCylinder.cpp [hunk 5]
```diff
@@ -118,13 +118,11 @@ void WrapCylinder::extendFinalizeFromProperties()
...
-        string errorMessage = getProperty_radius().getName()
-            + " is not specified or is negative.";
-        OPENSIM_THROW_FRMOBJ(InvalidPropertyValue,
-            getProperty_radius().getName(), errorMessage);
-    }
+    OPENSIM_THROW_IF_FRMOBJ(
+        get_radius() < 0,
+        InvalidPropertyValue,
+        getProperty_radius().getName(),
+        "Radius must be specified and cannot be less than zero");
```
Comment (chrisdembia) [inline OpenSim/Simulation/Wrap/WrapCylinder.cpp]: Just curious: What led you to update these error checks? It doesn't look like you changed the constructor to `InvalidPropertyValue` or anything like that.

File: OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp (hunk 3 above)
Comment (aseth1) [reply OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: Good catch @chrisdembia. I think the pattern for any subcomponent would work, since it is a mechanism of caching and restoring its properties and not its state. I have slight preference for the copy constructor.

File: OpenSim/Simulation/Wrap/WrapCylinder.cpp (hunk 5 above)
Comment (aseth1) [reply OpenSim/Simulation/Wrap/WrapCylinder.cpp]: I appreciate the additions/correction (goes beyond the call of duty for this PR) as part of the sweep to add meaningful messages. I think it is fine leave it in here- please don't spend the time to separate at this point.

File: OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp (hunk 3 above)
Comment (tkuchida) [reply OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: Thanks @chrisdembia. I guess I misinterpreted Ajay's instructions. I'll change to copy constructor.

File: OpenSim/Simulation/Wrap/WrapCylinder.cpp (hunk 5 above)
Comment (chrisdembia) [reply OpenSim/Simulation/Wrap/WrapCylinder.cpp]: Of course; I did not mean that these changes should be separated. Ignore the question.

Comment (tkuchida) [reply OpenSim/Simulation/Wrap/WrapCylinder.cpp]: Ajay wanted the exceptions in the `MuscleFixedWidthPennationModel` and `MuscleRebellionActivationDynamicModel` `extendFinalizeFromProperties()` methods changed to `InvalidPropertyValue`, so I changed them by following examples elsewhere in the repo. I then got more comments saying that my use of `InvalidPropertyValue` was poor, so I updated all uses of `InvalidPropertyValue` in the repo so that doesn't happen again.

Comment (aseth1) [reply OpenSim/Simulation/Wrap/WrapCylinder.cpp]: Thanks @tkuchida!

File: OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp (hunk 3 above)
Comment (tkuchida) [reply OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: @chrisdembia & @aseth1 - Have you ever considered removing `clone()` from the public interface? One could argue that I should have known better, but I wouldn't have eaten the poison if the API hadn't left it in the kitchen---and I don't use a poison detector in my workflow. User-centered design principle: error prevention.

**Comment by tkuchida** [comment]
Thanks @chrisdembia.
@jimmyDunne Would you please add a task to verify in the GUI? :car: Thanks!
