### PR TITLE
Fix error cases with Component::findStateVariable().

### LINKED ISSUE #2082: Component::getStateVariableValue() silently accepts incorrect paths
The line `model.getStateVariableValue("typo/tx/value")` returns the state variable with path `"planar/tx/value"` (if it exists). This is because if `findStateVariable()` can't find a component at the specified path, it looks for a component anywhere with the name `tx` with a state variable `value`.

Furthermore, if both `compA` and `compB` have a state variable named `"myvar"`  and `compB` is a subcomponent of `compA`, the line `compA.getStateVariableValue("compB/myvar")` will return the value of `compA`'s state variable, *not* `compB`'s state variable.

I'm working on a fix.

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes #2082 

### Brief summary of changes

- This PR fixes the two bugs mentioned in #2082. Invalid state variable paths were silently being accepted, and sometimes the wrong state variable value could be returned.

### Testing I've completed

- Added a test case that failed without this PR. With the bug fix, the tests now pass.

### Looking for feedback on...

- Is the use of ComponentPath okay?

### CHANGELOG.md (choose one)

- no need to update because...this bug was introduced after 3.3.

### CODE REVIEW

File: OpenSim/Common/Test/testComponentInterface.cpp [hunk 1]
```diff
@@ -1046,6 +1046,42 @@ void testComponentPathNames()
...
+    SimTK_TEST(top.getStateVariableValue(s, "internalSub/subState") == 10);
+    SimTK_TEST(top.getStateVariableValue(s, "a/subState") == 20);
+    SimTK_TEST(top.getStateVariableValue(s, "a/b/subState") == 30);
+    SimTK_TEST(a->getStateVariableValue(s, "subState") == 20);
+    SimTK_TEST(a->getStateVariableValue(s, "b/subState") == 30);
+    SimTK_TEST(b->getStateVariableValue(s, "subState") == 30);
+    SimTK_TEST(b->getStateVariableValue(s, "../subState") == 20);
+    SimTK_TEST(b->getStateVariableValue(s, "../../internalSub/subState") == 10);
+
+    top.getStateVariableValue(s, "a/b/subState");
```
Comment (tkuchida) [inline OpenSim/Common/Test/testComponentInterface.cpp]: I don't think L1079 is necessary (see L1072).

**Comment by chrisdembia** [comment]
Thanks @tkuchida

**Comment by chrisdembia** [comment]
@aseth1 thanks for your review. I renamed the function.

> (made possible by your changes to include the path in updateFromXMLNode in #1751).

I'm not sure this is true. `findStateVariable()` could only be used after `finalizeFromProperties()`, during which I think all the socket paths are corrected (even without #1751), because of the logic here:

https://github.com/opensim-org/opensim-core/blob/8d6db79fdfdcda7ad073092d2d65411886b74b95/OpenSim/Common/Component.h#L3004-L3011


Ready for review again.

File: OpenSim/Common/Component.h [hunk 2]
```diff
@@ -2355,11 +2355,18 @@ OpenSim_DECLARE_ABSTRACT_OBJECT(Component, Object);
...
 #ifndef SWIG // StateVariable is protected.
     /**
-     * Find a StateVariable of this Component (includes its subcomponents).
+     * Get a StateVariable anywhere in the Component tree, given a
+     * StateVariable path. The StateVariable doesn't need to be in a
+     * subcomponent of this compoonent; it could be located in a different
+     * branch of the Component tree (in such a case, the specified path might
+     * begin with "../").
+     * This returns nullptr if a StateVariable does not exist at the specified
+     * path or if the path is invalid.
```
Comment (aseth1) [inline OpenSim/Common/Component.h]: 👍

**Comment by aseth1** [comment]
@chrisdembia the travis push build failure looks like a legit test failure.

**Comment by chrisdembia** [comment]
Ready for review again.

**Comment by chrisdembia** [comment]
This PR has 2 reviews and passes CI. Would either reviewer (@tkuchida or @aseth1) be interested in merging this?

**Comment by tkuchida** [comment]
Re-reviewed and looks :+1:; merging.

**Comment by chrisdembia** [comment]
Thanks @tkuchida
