### PR TITLE
Fixes Hopper example: wrapping of device over patella

### LINKED ISSUE #1494: Hopper example no longer hops
Step 3 in exampleHopperDevice_answers.cpp should show the hopper hopping.

### PR DESCRIPTION
**Pull request by chrisdembia**
This PR fixes an issue that Tom pointed out in #1494. The path to the patella has changed. 

This PR also cleans up a few other things. I tested locally on my Mac and all 3 parts of the example ran fine.

Fixes #1494

### CODE REVIEW

**Comment by chrisdembia** [comment]
Your changes look good to me as well.

File: OpenSim/Examples/ExampleHopperDevice/exampleHopperDevice.cpp [hunk 1]
```diff
@@ -90,17 +90,15 @@ void connectDeviceToModel(OpenSim::Device& device, OpenSim::Model& model,
     //      modelFrameBname), then connect them to the parent frames of each
     //      anchor. (2 lines of code for each anchor.)
 
-    // Add the device to the model. We need to add the device using
-    // addModelComponent() rather than addComponent() because of a bug in
-    // Model::initSystem().
-    model.addModelComponent(&device);
+    // Add the device to the model.
+    model.addComponent(&device);
```
Comment (aseth1) [inline OpenSim/Examples/ExampleHopperDevice/exampleHopperDevice.cpp]: :+1:

**Comment by chrisdembia** [comment]
Thank you!
