### PR TITLE
Fix bug in Millard2012EquilibriumMuscle

### LINKED ISSUE #1357: Millard2012Equilibrium Muscle - fiberStiffnessAlongTendon  incorrect calculation
In calcMuscleDynamicsInfo, mdi.fiberStiffnessAlongTendon is calculated:

`dFmAT_dlceAT = calc_DFiberForceAT_DFiberLengthAT(dFm_dlce, mli.sinPennationAngle, mli.cosPennationAngle, mli.fiberLength);`

The first argument provided is _dFm_dlce_  (muscle stiffness), change in force along **the fiber** / lce.  But the method requires:

`double Millard2012EquilibriumMuscle::calc_DFiberForceAT_DFiberLengthAT(double dFmAT_d_lce, double sinPhi, double cosPhi,double lce) const`

 where  _dFmAT_d_lce_ is the change in force along **the tendon**/ lce

I verified that calc_DFiberForceAT_DFiberLengthAT is written to use dFmAT_d_lce, so it is being provided the wrong parameter when  invoked in  calcMuscleDynamicsInfo.

### PR DESCRIPTION
**Pull request by tkuchida**
I checked the related calculations and they appear to be correct. None of the other calls to `calc_DFiberForceAT_DFiberLength()` are thusly affected. Reported by @humphreysb :rocket:. Fixes #1357.

### CODE REVIEW

**Comment by jenhicks** [comment]
@humphreysb Would you mind reviewing this PR? Thanks!

File: OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp [hunk 1]
```diff
@@ -895,7 +895,11 @@ calcMuscleDynamicsInfo(const SimTK::State& s, MuscleDynamicsInfo& mdi) const
             dFm_dlce = calcFiberStiffness(fiso, a,
                                           mvi.fiberForceVelocityMultiplier,
                                           mli.normFiberLength, optFiberLen);
-            dFmAT_dlceAT = calc_DFiberForceAT_DFiberLengthAT(dFm_dlce,
+            const double dFmAT_dlce =
+                calc_DFiberForceAT_DFiberLength(fm, dFm_dlce, mli.fiberLength,
+                                                mli.sinPennationAngle,
+                                                mli.cosPennationAngle);
+            dFmAT_dlceAT = calc_DFiberForceAT_DFiberLengthAT(dFmAT_dlce,
                 mli.sinPennationAngle, mli.cosPennationAngle, mli.fiberLength);
```
Comment (aseth1) [inline OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: @humphreysb can you confirm that your issue is resolved by this change. Thanks!

Comment (humphreysb) [inline OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: Yes  - will take a look.  And sorry @jenhicks , I completely missed your request for review somehow.

Comment (humphreysb) [inline OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp]: After review, LGTM.  Thanks @aseth1, @tkuchida , @jenhicks !
